### DISCUSSION TITLE
Receive no Data

### DISCUSSION THREAD

**Discussion by LaMiyu** [alengwenus/esphome_components#5] [Q&A] [answered]
Hi there,

Until a few days ago I used an ESP8266 with Tasmota to read my electricity meter. But since my Tasmota was messing around every time HA was restarted (various scripts, SetOption19 etc. tested) I was looking for an alternative ...

I was very happy to see your solution as I already have some esphome solutions in use.

Unfortunately, I am not receiving any data from my ESP; (
![image](https://user-images.githubusercontent.com/73053267/146029288-4852cfd2-b682-4f4e-ad91-b571ee8bdd2a.png)

For Tasmota I had a ready-made solution:
[https://tasmota.github.io/docs/Smart-Meter-Interface/#ebz-dd3-obis](https://tasmota.github.io/docs/Smart-Meter-Interface/#ebz-dd3-obis)

This is my ESP config
![image](https://user-images.githubusercontent.com/73053267/146029708-f5fb63f1-04bd-46df-af43-90d6b251c57c.png)

I don't understand why I don't see any information in the log except the initials ...
Do you have any idea where my mistake is?

**Comment by alengwenus** [comment]
Your configuration looks good to me. Could you recheck the wiring?
What smartmeter do you have?

**Reply by LaMiyu** [reply]
Hi,

I use the eBZ DD3.
With a Hitchi reading head.

The cables are all "correct" at least on the reading head and also on the ESP. Yesterday in the same configuration only with Tasmota instead of ESPhome I also received the data ;_; I don't understand why I don't see any data in the log; (

**Comment by alengwenus** [comment]
According to the manual there are two types of the eBZ DD3 with different UART settings.
Type OD (7, even,1) and SM (8, none, 1). Maybe you have the OD type?

**Reply by LaMiyu** [reply]
I tested this:
```
uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 7
  parity: EVEN
  stop_bits: 1
```
unfortunately without success ...

I already have it with and without:
```
  includes:
    - uart_read_line_sensor.h
```

tested - unfortunately that doesn't help either; (

**Comment by LaMiyu** [comment, marked as answer]
To make sure that no cables or the reading head are broken, I have now set up and reconnected a second ESP8266 with Tasmota.

Briefly drawn the script on it:
```
>D
>B
TelePeriod 30
=>sensor53 r
>M 1
; Device: eBZ DD3 2R06 ODZ1
; protocol is D0 OBIS ASCII
; 9600@7E1 for OP-type devices, 9600@8N1 for SM-type devices
+1,3,o,0,9600,SM,1
; Zählerstand zu +A, tariflos, 
; Zählerstände Auflösung 10 µW*h (6 Vorkomma- und 8 Nachkommastellen)
1,1-0:1.8.0*255(@0.001,Energie Bezung,Wh,1_8_0,8
; Zählerstand zu +A, Tarif 1
1,1-0:1.8.1*255(@0.001,Energie Bezung T1,Wh,1_8_1,8
; Zählerstand zu +A, Tarif 2
1,1-0:1.8.2*255(@0.001,Energie Bezung T2,Wh,1_8_2,8
; Zählerstand zu -A, tariflos
1,1-0:2.8.0*255(@0.001,Energie Export,Wh,2_8_0,8
; Summe der Momentan-Leistungen in allen Phasen, Auflösung 0,01W (5 Vorkomma- und 2 Nachkommastellen)
1,1-0:16.7.0*255(@1,Leistung,W,16_7_0,18
; Momentane Leistung in Phase Lx, Auflösung 0,01W (5 Vorkomma- und 2 Nachkommastellen)
1,1-0:36.7.0*255(@1,Leistung L1,W,36_7_0,18
1,1-0:56.7.0*255(@1,Leistung L2,W,56_7_0,18
1,1-0:76.7.0*255(@1,Leistung L3,W,76_7_0,18
; Spannung in Phase Lx, Auflösung 0,1V (nur über MSB)
1,1-0:32.7.0*255(@1,Spannung L1,V,32_7_0,1
1,1-0:52.7.0*255(@1,Spannung L2,V,52_7_0,1
1,1-0:72.7.0*255(@1,Spannung L3,V,72_7_0,1
; Statuswort, 4 Byte Information über den Betriebszustand, HEX string
; tasmota can decode one string per device only!
;1,1-0:96.5.0*255(@#),Status1,,96_5_0,0
;1,1-0:96.8.0*255(@#),Status2,,96_8_0,0
; Geräte-Identifikation, Nach DIN 43863-5 
1,1-0:96.1.0*255(@#),Identifikation,,96_1_0,0
;1,1-0:0.0.0*255(@#),Identifikation,,0_0_0,0
#
```
and it works:
![image](https://user-images.githubusercontent.com/73053267/146134207-c668e738-fa2f-4a3d-af96-c9c5fa451397.png)
![image](https://user-images.githubusercontent.com/73053267/146134246-7825ae93-e83e-4f0d-9fbd-97498b36548f.png)


So it must be due to my ESPhome ... do you have any ideas what I might have done wrong?

```
external_components:
  - source:
      type: git
      url: https://github.com/alengwenus/esphome_components.git
      ref: main
    components: [ sml ]


esphome:
  name: strom-keller
  platform: ESP8266
  board: nodemcuv2
  includes:
    - uart_read_line_sensor.h

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0


# Enable Home Assistant API
api:

#external_components:
#  - source: github://pr#2396
#    components: [ sml ]


ota:
  password: --------------

wifi:
  ssid: --------------
  password: --------------

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Strom-Keller Fallback Hotspot"
    password: "yEFWbpBi4j63"
    
  manual_ip:
    static_ip: 192.168.178.128
    gateway: 192.168.178.1
    subnet: 255.255.255.0

time:
  - platform: homeassistant

captive_portal:

web_server:
  port: 80

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 7
#  data_bits: 8
  parity: EVEN
#   parity: NONE
  stop_bits: 1

sml:
  id: mysml
  uart_id: uart_bus

sensor:
  - platform: sml
    name: "Total energy"
#    sml_id: mysml
    server_id: "01 00 01 08 00 FF"
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001

  - platform: sml
    name: "Energy Export"
#    sml_id: mysml
#    server_id: "0123456789abcdef"
    obis_code: "1-0:2.8.0"
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01


  - platform: sml
    name: "Active power"
#    sml_id: mysml
#    server_id: "0123456789abcdef"
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

text_sensor:
  - platform: sml
    name: "Manufacturer"
#    sml_id: mysml
    obis_code: "129-129:199.130.3"
    format: text

  - platform: sml
    name: "Total energy text"
#    sml_id: mysml
    obis_code: "1-0:1.8.0"

```
