### ISSUE TITLE
Question about Hager OBIS codes

### ISSUE THREAD

**Issue by Bouni** [alengwenus/esphome_components#13]
Hi, 

first of all thank you so much for this awesome ESPHome integration :-)

I worked for the last two years on a PCB that allows me to read out my two smart meters. It was set aside because of various reasons but finally I managed to get it working 🥳 

![grafik](https://user-images.githubusercontent.com/948965/212102773-032c7aed-5086-46c0-a6ff-1fc4d4e199d4.png)

So currently I work on the ESPhome config. So far everyhing is clear, I used the HAGER documentation for the OBIS codes:

https://hager.com/de/katalog/download/product/asset/file/22DE0001-TECHNIK-EHZ.PDF/

Entries like `01 00 01 08 00 FF Zählerstand Totalregister` are totally clear, the notation is in HEX so `01 00 01 08 00` becomes `1-0:1.8.0`.
What the `FF` means is not clear to me.

But the document further down the list has these entries:

```
01 00 60 32 03 03 Spannungsminimum
01 00 60 32 03 04 Spannungsmaximum
01 00 60 32 00 03 Minimale Chiptemperatur
01 00 60 32 00 04 Maximale Chiptemperatur
01 00 60 32 00 05 Gemittelte Chiptemperatur
```

The first 2would share the same OBIS code, the same goes for the last 3.
Any ideas how this works or how the OBIS code has to be set in order to get these measurements?

**Comment by the78mole** [comment]
Hi Bouni,

The OBIS Codes are standardized identifiers for measurement values and have the syntax: `A-B:C.D.E*F` The alphabetic characters [A...F] each representing a byte value, the symbols [-:.*] are just seperators to make them more readable. The default representation uses decimal coding (0...255). Meaning FF = 255

In short, simply convert hex to decimal and put it together with the seperators like that:

```
01 00 01 08 00 FF -> 1-0:1.8.0*255
01 00 60 32 03 03 -> 1-0:96.50.3*3
01 00 60 32 03 04 -> 1-0:96.50.3*3
```
FF = 255 is also widely used for summing values, as far as I remember.

Hope this helps.

Regards,
Daniel

**Comment by alengwenus** [comment]
As far as I remember the last part of the OBIS number (*...) is not supported by this component. I simply did not knew about it.
I will have a look into the code. Maybe it's not that hard to implement.

**Comment by Bouni** [comment]
@the78mole Thanks for the detailed explanation, highly appreciate it 😊 

@alengwenus That would be awesome, te component ist already more than awesome. As soon as I finished my project I'll open source it and maybe make it available on Tindie or a similar platform for sale.

Here's a picture of the board in a freshly printed case on my test meter on my bench:

![grafik](https://user-images.githubusercontent.com/948965/212261008-f569603d-0f20-4998-8b00-2c8bdd95adfb.png)

@alengwenus do you have any kind of support page (buymeacoffee / Ko-Fi / patreon / ...) so that I can send you a small donation?

**Comment by alengwenus** [comment]
@Bouni I implemented the optional 6th byte in the OBIS code (main branch).
In your configuration you may now use:
`obis_code: "A-B:C.D.E*F"`
as well as
`obis_code: A-B:C.D.E`.
In the latter case the `*255` is appended automatically as a default value.
It would be great if you could test it, please.

Please note, that I only implemented it in this custom component. It's not yet integrated in the [SML ESPHome component](https://esphome.io/components/sml.html). As soo as you confirm functionality, I'll catch up.

**Comment by Bouni** [comment]
Sure, I'll test it in my lunch break and let you know!

Just to be sure, I need to use this component like this, right?

```
external_components:
  - source: github.com/alengwenus/esphome_components@main
    components: [ sml ]
```

Hopefully this will then be merged into the ESPHome comonent as well!

**Comment by alengwenus** [comment]
Yes, that should do.
And if everything works well, feel free to use this link: https://www.buymeacoffee.com/alengwenus :-)

**Comment by Bouni** [comment]
Seems to work 🥳 

![grafik](https://user-images.githubusercontent.com/948965/212313243-78810827-cc28-4eaa-9ba6-d396e0d4962d.png)

```
- platform: sml
  name: "Chip temperature"
  obis_code: "1-0:96.50.0*2"
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  device_class: temperature
  state_class: measurement
  filters:
    - multiply: 0.1

- platform: sml
  name: "Chip temperature minimum"
  obis_code: "1-0:96.50.0*3"
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  device_class: temperature
  state_class: measurement

- platform: sml
  name: "Chip temperature maximum"
  obis_code: "1-0:96.50.0*4"
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  device_class: temperature
  state_class: measurement

- platform: sml
  name: "Chip temperature mean"
  obis_code: "1-0:96.50.0*5"
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  device_class: temperature
  state_class: measurement

- platform: sml
  name: "Voltage minimum"
  obis_code: "1-0:96.50.3*3"
  unit_of_measurement: V
  accuracy_decimals: 1
  device_class: voltage
  state_class: measurement

- platform: sml
  name: "Voltage maximum"
  obis_code: "1-0:96.50.3*4"
  unit_of_measurement: V
  accuracy_decimals: 1
  device_class: voltage
  state_class: measurement      
```
